[tool.poetry]
name = "codaio"
version = "0.2.0"
description = "Python wrapper for Coda.io API"
authors = ["MB <mb@blaster.ai>"]
license = "MIT"
readme='README.md'
homepage='https://github.com/Blasterai/codaio'

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"
attrs = "^19.1"
python-dateutil = "^2.8"
inflection = "^0.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.1"
coverage = "^4.5"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
